### PR TITLE
[MDOCCK-35] - Upgrade Http Client

### PR DESCRIPTION
**Pull request by timtebeek**
For https://issues.apache.org/jira/browse/MDOCCK-35

### CODE REVIEW

**Review by MartinKanters — APPROVED** [review]
It's looking good to me! @michael-o do you want to take another look (I see @rfscholte asked you for a review specifically)?

**Comment by timtebeek** [comment]
Posted some comments in the issue, which might be best to repeat here to ensure they're seen before a merge:
> Had to move HttpClient builder to execute method, as proxy setup was in execute.
> Following redirects seems to be the default, hence no direct 1 to 1 replacement for that.
> The only thing I couldn't work out a direct parallel for was preemptive authentication with the proxy.
There might be some hints in here if that's still needed:
https://github.com/apache/httpcomponents-client/blob/5.0.x/httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientPreemptiveBasicAuthentication.java

**Comment by MartinKanters** [comment]
Thanks @timtebeek for the extra warning. Preemptive authentication are things I did not know about yet, so before merging I wanted to make sure that nothing would break. I've tested the 1.1 build and yours against a local proxy with authentication to check the differences. My test target was the maven-help-plugin. Both showed the following warnings in the logs per host: 
```
May 14, 2021 9:43:58 AM org.apache.commons.httpclient.HttpMethodDirector authenticateHost
WARNING: Required credentials not available for BASIC <any realm>@www.apache.org:443
May 14, 2021 9:43:58 AM org.apache.commons.httpclient.HttpMethodDirector authenticateHost
WARNING: Preemptive authentication requested but no default credentials available
```
The authentication however works fine in the end, and since there is no functional regression between the two, I'm going ahead and merge it.

**Comment by MartinKanters** [comment]
Thanks for contributing @timtebeek !

**Comment by MartinKanters** [comment]
I've made a mistake while testing. So I redid the testing and luckily still did not find any regression. The warning logs I mentioned before are gone now, though.

**Pull request merged**
